version: '3.5'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db/mongodb/data:/data/db
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all --logpath=/dev/null # --quiet

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/config/redis.conf:/etc/redis/redis.conf
      - ./db/redis/data:/opt/data
      - ./db/redis/log:/opt/log
    command: redis-server /etc/redis/redis.conf
    privileged: true

  deliver:
    build: .
    links:
      - mongodb
      - redis
    container_name: lark-treasure-chest-deliver
    restart: on-failure
    ports:
      - "7776:7776"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_PORT=27017
      - MONGODB_SCHEMA=deliver_kit
      - MONGODB_USERNAME=deliver_kit
      - MONGODB_PASSWORD=123456
      - MONGODB_HOST=mongodb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_PASSWORD=123456
      - LOG_LEVEL=DEBUG
    depends_on:
      - mongodb
      - redis