version: '3.5'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/db/data
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db/data:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all --logpath=/dev/null # --quiet

  web:
    build: .
    links:
      - mongodb
    container_name: BRS-Service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - MONGODB_PORT=27017
      - MONGODB_SCHEMA=brs
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb